name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  black-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
